import type { DomainErrorCode } from '../../domain/constants/errors';

export enum ApplicationErrorCode {
  INVALID_PROVIDER = 'INVALID_PROVIDER',
  INVALID_REFERENCE = 'INVALID_REFERENCE',
  INVALID_EXTERNAL_TRANSACTION = 'INVALID_EXTERNAL_TRANSACTION',
  INVALID_EXTERNALTRANSACTION = 'INVALID_EXTERNALTRANSACTION',
  INVALID_IDEMPOTENCY_KEY = 'INVALID_IDEMPOTENCY_KEY',
  INVALID_PLAYER = 'INVALID_PLAYER',
  INVALID_WALLET = 'INVALID_WALLET',
  INVALID_ROUND = 'INVALID_ROUND',
  INVALID_GAME = 'INVALID_GAME',
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  INVALID_TRANSACTION = 'INVALID_TRANSACTION',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  UNKNOWN_MONEY_FIELD = 'UNKNOWN_MONEY_FIELD',
  UNKNOWN_FIELD = 'UNKNOWN_FIELD',
  INVALID_KIND = 'INVALID_KIND',
  REFERENCE_NOT_ALLOWED = 'REFERENCE_NOT_ALLOWED',
  WALLET_ALREADY_EXISTS = 'WALLET_ALREADY_EXISTS',
  MESSAGE_PAYLOAD_CONFLICT = 'MESSAGE_PAYLOAD_CONFLICT',
  IDEMPOTENCY_PAYLOAD_CONFLICT = 'IDEMPOTENCY_PAYLOAD_CONFLICT',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  EXTERNAL_TRANSACTION_CONFLICT = 'EXTERNAL_TRANSACTION_CONFLICT',
  INVALID_MESSAGE_JSON = 'INVALID_MESSAGE_JSON',
  INVALID_MESSAGE_ENVELOPE = 'INVALID_MESSAGE_ENVELOPE',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  INVALID_LIMIT = 'INVALID_LIMIT',
  INVALID_CURSOR = 'INVALID_CURSOR',
  IDEMPOTENCY_KEY_MUST_BE_HEADER = 'IDEMPOTENCY_KEY_MUST_BE_HEADER',
  INVALID_REQUEST = 'INVALID_REQUEST',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
  INVALID_BEARER_TOKEN = 'INVALID_BEARER_TOKEN',
  PROVIDER_IDENTITY_MISMATCH = 'PROVIDER_IDENTITY_MISMATCH',
  AUTH_CONFIGURATION_INVALID = 'AUTH_CONFIGURATION_INVALID',
}

export enum IdentifierField {
  PROVIDER = 'provider',
  REFERENCE = 'reference',
  EXTERNAL_TRANSACTION = 'external_transaction',
  EXTERNAL_TRANSACTION_PARAM = 'externalTransaction',
  IDEMPOTENCY_KEY = 'idempotency_key',
  PLAYER = 'player',
  WALLET = 'wallet',
  ROUND = 'round',
  GAME = 'game',
  MESSAGE = 'message',
  TRANSACTION = 'transaction',
}

export enum PersistenceErrorCode {
  UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
}

export const identifierErrorCodes: Record<IdentifierField, ApplicationErrorCode> = {
  [IdentifierField.PROVIDER]: ApplicationErrorCode.INVALID_PROVIDER,
  [IdentifierField.REFERENCE]: ApplicationErrorCode.INVALID_REFERENCE,
  [IdentifierField.EXTERNAL_TRANSACTION]: ApplicationErrorCode.INVALID_EXTERNAL_TRANSACTION,
  [IdentifierField.EXTERNAL_TRANSACTION_PARAM]: ApplicationErrorCode.INVALID_EXTERNALTRANSACTION,
  [IdentifierField.IDEMPOTENCY_KEY]: ApplicationErrorCode.INVALID_IDEMPOTENCY_KEY,
  [IdentifierField.PLAYER]: ApplicationErrorCode.INVALID_PLAYER,
  [IdentifierField.WALLET]: ApplicationErrorCode.INVALID_WALLET,
  [IdentifierField.ROUND]: ApplicationErrorCode.INVALID_ROUND,
  [IdentifierField.GAME]: ApplicationErrorCode.INVALID_GAME,
  [IdentifierField.MESSAGE]: ApplicationErrorCode.INVALID_MESSAGE,
  [IdentifierField.TRANSACTION]: ApplicationErrorCode.INVALID_TRANSACTION,
};

export type RequestErrorCode = DomainErrorCode | ApplicationErrorCode;
