export enum FinancialErrorCode {
  UNBALANCED_LEDGER = 'UNBALANCED_LEDGER',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  AMOUNT_LIMIT_EXCEEDED = 'AMOUNT_LIMIT_EXCEEDED',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  REFERENCE_REQUIRED = 'REFERENCE_REQUIRED',
  INVALID_TRANSACTION_STATE = 'INVALID_TRANSACTION_STATE',
  INBOX_ALREADY_PROCESSED = 'INBOX_ALREADY_PROCESSED',
  OUTBOX_ALREADY_PUBLISHED = 'OUTBOX_ALREADY_PUBLISHED',
  PLAYER_MISMATCH = 'PLAYER_MISMATCH',
  REVERSAL_INSUFFICIENT_FUNDS = 'REVERSAL_INSUFFICIENT_FUNDS',
  REFERENCE_CONTEXT_MISMATCH = 'REFERENCE_CONTEXT_MISMATCH',
  REFERENCE_KIND_INVALID = 'REFERENCE_KIND_INVALID',
  REFERENCE_AMOUNT_MISMATCH = 'REFERENCE_AMOUNT_MISMATCH',
  REFERENCE_NOT_PROCESSED = 'REFERENCE_NOT_PROCESSED',
  REFERENCE_ALREADY_REVERSED = 'REFERENCE_ALREADY_REVERSED',
  REFERENCE_NOT_FOUND = 'REFERENCE_NOT_FOUND',
  REFERENCE_TIMEOUT = 'REFERENCE_TIMEOUT',
  PERMANENT_INFRASTRUCTURE_FAILURE = 'PERMANENT_INFRASTRUCTURE_FAILURE',
  RETRY_EXHAUSTED = 'RETRY_EXHAUSTED',
}

export type DomainErrorCode =
  | FinancialErrorCode.UNBALANCED_LEDGER
  | FinancialErrorCode.INVALID_AMOUNT
  | FinancialErrorCode.INVALID_CURRENCY
  | FinancialErrorCode.AMOUNT_LIMIT_EXCEEDED
  | FinancialErrorCode.CURRENCY_MISMATCH
  | FinancialErrorCode.INSUFFICIENT_FUNDS
  | FinancialErrorCode.REFERENCE_REQUIRED
  | FinancialErrorCode.INVALID_TRANSACTION_STATE
  | FinancialErrorCode.INBOX_ALREADY_PROCESSED
  | FinancialErrorCode.OUTBOX_ALREADY_PUBLISHED;

export type WagerFailureCode =
  | FinancialErrorCode.INVALID_AMOUNT
  | FinancialErrorCode.AMOUNT_LIMIT_EXCEEDED
  | FinancialErrorCode.CURRENCY_MISMATCH
  | FinancialErrorCode.INSUFFICIENT_FUNDS
  | FinancialErrorCode.PLAYER_MISMATCH
  | FinancialErrorCode.REVERSAL_INSUFFICIENT_FUNDS
  | FinancialErrorCode.REFERENCE_CONTEXT_MISMATCH
  | FinancialErrorCode.REFERENCE_KIND_INVALID
  | FinancialErrorCode.REFERENCE_AMOUNT_MISMATCH
  | FinancialErrorCode.REFERENCE_NOT_PROCESSED
  | FinancialErrorCode.REFERENCE_ALREADY_REVERSED
  | FinancialErrorCode.REFERENCE_NOT_FOUND
  | FinancialErrorCode.REFERENCE_TIMEOUT
  | FinancialErrorCode.PERMANENT_INFRASTRUCTURE_FAILURE
  | FinancialErrorCode.RETRY_EXHAUSTED;
