export enum DemoErrorCode {
  INVALID_ORIGIN = 'INVALID_ORIGIN',
  INVALID_SESSION = 'INVALID_SESSION',
  INVALID_BET = 'INVALID_BET',
  INVALID_MULTIPLIER = 'INVALID_MULTIPLIER',
  CREATE_SESSION_FIRST = 'CREATE_SESSION_FIRST',
  RETRY_PENDING_OPERATION = 'RETRY_PENDING_OPERATION',
  PEER_NOT_FOUND = 'PEER_NOT_FOUND',
  BET_NOT_FOUND = 'BET_NOT_FOUND',
  FINISH_CURRENT_ROUND = 'FINISH_CURRENT_ROUND',
  BETTING_CLOSED = 'BETTING_CLOSED',
  STAKE_RANGE_001_100 = 'STAKE_RANGE_001_100',
  INVALID_PEERS = 'INVALID_PEERS',
  PEER_ALREADY_BET = 'PEER_ALREADY_BET',
  ROUND_ALREADY_STARTED = 'ROUND_ALREADY_STARTED',
  CASHOUT_CLOSED = 'CASHOUT_CLOSED',
  CANCEL_CLOSED = 'CANCEL_CLOSED',
  NO_WIN_TO_ROLLBACK = 'NO_WIN_TO_ROLLBACK',
  REPLAY_EXISTING_ROLLBACK = 'REPLAY_EXISTING_ROLLBACK',
  UNSETTLED_BET = 'UNSETTLED_BET',
  OPERATION_NOT_FOUND = 'OPERATION_NOT_FOUND',
  DEMO_UNAVAILABLE = 'DEMO_UNAVAILABLE',
}

export class DemoRequestError extends Error {
  constructor(
    readonly status: number,
    readonly code: DemoErrorCode,
  ) {
    super(code);
  }
}
